### ISSUE TITLE
Combined Masternode and Stake Reward

### ISSUE THREAD

**Issue by Droopier** [wagerr/wagerr#48] opened 2018-08-04 20:22 UTC
This issue tracker is only for technical issues related to Wagerr Core.
General Wagerr questions and/or support requests and are best directed to the [Wagerr Discord](https://discord.wagerr.com).

### Describe the issue
- Wallet presents a MN reward and stake reward as combined reward (3.79998520) and credited to the staking wallet.

### Can you reliably reproduce the issue?
- No
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen

-Two transaction crediting two respective wallets

### Actual behavior
- One transaction crediting one wallet is shown in GUI.
- The transaction itself in block explorer is correct.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![screen shot](https://user-images.githubusercontent.com/42042714/43680317-0bf53b18-9806-11e8-8f27-f23fda11e614.png)

### What version of Wagerr Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
- Wagerr Core version v1.5.0.0-be4caf5-dirty-Vegas (64-bit)

### Machine specs:
- OS: Mac High Sierra 10.13.4
- CPU: Intel i7 2.7ghz
- RAM: 16gb
- Disk size: 500gb
- Disk Type (HD/SDD): HD SATA

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

- TXid:dc10d578275da8b9319d65d3e66bea99eba9fe04e1396afc9add50318640336a

**Comment by zeroedge83** [comment] 2018-08-17 11:52
Doesnt look like a issue, just a very lucky occurence of getting both rewards.

**Comment by trappist** [comment] 2018-09-19 05:45
Check the transaction details in block explorer or debug console. Most likely these were two outputs on the same transaction, not two transactions presented as one.

**Comment by WagerrTor** [comment] 2018-12-20 00:57
Is this still open?

**Comment by WagerrTor** [comment] 2018-12-20 16:32
Please check if the issue is resolved with newer version as we have few since v1.5. I will close this issue, please feel free to reopen if you think that ther is still some issue.

**Closed as completed by WagerrTor** 2018-12-20 16:32 UTC
Labels: Questions and Help
