### ISSUE TITLE
Timeline High Sierra build?

### ISSUE THREAD

**Issue by ChristBKK** [wagerr/wagerr#12] opened 2018-02-22 09:08 UTC
Can you give us some timeline? Days or weeks? Thanks

**Comment by tools4** [comment] 2018-02-22 10:46
you can compile the source code for yourself.
![image](https://user-images.githubusercontent.com/36730224/36534133-a2518b10-1800-11e8-83aa-1af8ce164013.png)

**Comment by llthomps** [comment] 2018-02-24 16:13
I was able to compile 1.4.34.2 using the following configuration... 

`./configure LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" -with-boost=/opt/local/`

I also had to remove the following code from this file [/src/qt/wagerr.cpp](https://github.com/wagerr/wagerr/blob/25cf70fa84a9c0168097be9c222c15b55bf99777/src/qt/wagerr.cpp)

`#ifdef Q_OS_MAC
#if __clang_major__ < 4
    QString s = QSysInfo::kernelVersion();
    std::string ver_info = s.toStdString();
    // ver_info will be like 17.2.0 for High Sierra. Check if true and exit if build via cross-compile
    if (ver_info[0] == '1' && ver_info[1] == '7') {
        QMessageBox::critical(0, "Unsupported", BitcoinGUI::tr("High Sierra not supported with this build") + QString("\n\n"));
        ::exit(1);
    }
#endif
#endif`

**Comment by WagerrTor** [comment] 2018-02-25 21:34
thanks @llthomps for letting us know and helping.

@Cryptarchist can you try that?

**Comment by zeroedge83** [comment] 2018-02-26 12:30
@Kokary worth a try

**Comment by Cryptarchist** [comment] 2018-03-01 06:31
@ChristBKK @tools4 @llthomps I have uploaded High Sierra builds [here](https://github.com/wagerr/wagerr/releases/tag/v1.4.34.2) (labelled High Sierra only).

Please give them a go.

**Comment by llthomps** [comment] 2018-03-01 14:17
@Cryptarchist thanks, it works for me!

**Comment by Cryptarchist** [comment] 2018-03-01 22:55
@llthomps thanks for taking a look!

I will close this thread as the issue is now resolved.

**Closed as completed by Cryptarchist** 2018-03-01 22:55 UTC
Labels: Build system
