### ISSUE TITLE
Win 10 - wagerr-qt crashes from options window

### ISSUE THREAD

**Issue by Kordau** [wagerr/wagerr#4] opened 2018-02-20 23:00 UTC
wagerr-qt crashes when launched with -disablewallet

### Steps to reproduce
1. Launch with "wagerr-qt.exe -disablewallet"
2. Open "Options" window
3. Click "OK".

### Expected behavior
Options window should close and wagerr-qt continues running.

### Actual behavior
wagerr-qt closes unexpectedly.

### What version of Wagerr Core are you using?
- Wagerr Core version v1.4.34.0-Vegas (64-bit)
- It also happened on the original v1.4.33. I never tested other builds

### Machine specs:
- OS: Windows 10
- CPU: Intel i7
- RAM: 16GB
- Disk size: 2TB
- Disk Type : SSD + HD

##### From Debug.log...
```
GUI: setGeometry: Unable to set geometry 5x13+640+280 on QWidgetWindow/'QLabelClassWindow'. Resulting geometry:  120x13+640+280 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).
GUI: QObject::connect: Cannot connect QPushButton::clicked() to (null)::toggleLockWallet()
GUI: QObject::connect: Cannot connect QAction::triggered() to (null)::show()
GUI: QObject::connect: Cannot connect QAction::triggered() to (null)::hide()
2018-02-20 22:41:36 AppInit2 : parameter interaction: wallet functionality not enabled -> setting -staking=0
```

**Comment by WagerrTor** [comment] 2018-02-22 20:18
please try [latest release version](https://github.com/wagerr/wagerr/releases/latest), it is in v1.4.32.4 currently.

Note: please ensure to compile from clean sources if you did not already.

**Comment by WagerrTor** [comment] 2018-02-22 20:23
I tried now latest version and could not reproduce this behaviour. Daemon and QT versions start. I tested with latest release version.

I am closing this one, if you still (_or anybody_) still gets this error please reply here to reopen this issue.

**Closed as completed by WagerrTor** 2018-02-22 20:23 UTC
Labels: Bug
